# .github/workflows/manual-ci.yml
name: Run Cypress Tests Manually

on:
  workflow_dispatch: # Permite execução manual

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com Cypress
        run: npx cypress run
